'use client';

import './globals.css';
import { ChakraProvider } from '@chakra-ui/react';
import { Providers } from './providers';
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={''}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
